### ISSUE TITLE
netdna.bootstrapcdn.com blocked

### ISSUE THREAD

**Issue by Fusl** [uBlock-user/uMatrix-Hosts-List#2]
Commit b106a862fc74c16c24b54fd52070177ea4f5684e introduced `netdna.bootstrapcdn.com` into the `hosts.txt`. Many websites based on [Bootstrap](https://getbootstrap.com/) use this domain to include the basic `bootstrap.min.css` and `bootstrap-theme.min.css` files. Using your blacklist breaks the websites including resources from this domain.

**Comment by uBlock-user** [comment]
Post example of website breakage

**Comment by Fusl** [comment]
https://status.edis.at/ and http://minexmr.com/ are two that I often use but are missing the CSS resources.
