### ISSUE TITLE
discordapp.com blocked

### ISSUE THREAD

**Issue by Fusl** [uBlock-user/uMatrix-Hosts-List#4]
7c07e7f5ed1c48bd2f1138c6e62c3c06f96554d6 adds `discordapp.com` to the blocklist preventing access to Discord. Why was this added?

**Comment by uBlock-user** [comment]
To prevent discord widget from loading as I consider that an annoyance. 

PS - This is a personal list of mine, so I add domains which I consider to be blocked or should be blocked.

**Comment by uBlock-user** [comment]
discordapp.com is also used on hanime.tv where images are pulled via that domain, so I will block the widget in uBO instead of here.
